Repository Integreat/cms, pull requests merged in 2018-10, with the labels that each got.

#833 [api-v3] remove array keys on site endpoint (fixes #832)
  wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
Labels: pr:review required, prio:high

#835 ig feedback improvements
  wp-content/plugins/ig-feedback/plugin.php
  wp-content/plugins/ig-feedback/stylesheet.css
  wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
Labels: pr:review required, prio:medium

#834 Fix APIv3 sites-endpoint, add FCM char count, improve feedback
  wp-content/plugins/firebase-notifications/js/jquery-simply-countable/README.md
  wp-content/plugins/firebase-notifications/js/jquery-simply-countable/jquery.simplyCountable.js
  wp-content/plugins/firebase-notifications/js/jquery-simply-countable/simplyCountable.jquery.json
  wp-content/plugins/firebase-notifications/js/send.js
  wp-content/plugins/firebase-notifications/notifications.php
  wp-content/plugins/ig-feedback/plugin.php
  wp-content/plugins/ig-feedback/stylesheet.css
  wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
  wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
Labels: pr:review required, prio:high

#837 Add i18n to Integreat Help plugin
  wp-content/plugins/ig-menu-help/lang/integreat-help-de_DE.mo
  wp-content/plugins/ig-menu-help/lang/integreat-help-de_DE.po
  wp-content/plugins/ig-menu-help/plugin.php
Labels: area:Functional, area:UI, pr:review required

#841 [wpml] hotfix for translation capabilities
  wp-content/plugins/wpml-translation-management/classes/class-wpml-tm-api.php
Labels: pr:review required

#842 i18n support for help plugin, hotfix for translation management
  wp-content/plugins/ig-menu-help/lang/integreat-help-de_DE.mo
  wp-content/plugins/ig-menu-help/lang/integreat-help-de_DE.po
  wp-content/plugins/ig-menu-help/plugin.php
  wp-content/plugins/wpml-translation-management/classes/class-wpml-tm-api.php
Labels: pr:review required

#784 Update FCM plugin
  wp-content/plugins/firebase-notifications/LICENSE
  wp-content/plugins/firebase-notifications/README.md
  wp-content/plugins/firebase-notifications/classes/database.php
  wp-content/plugins/firebase-notifications/classes/service.php
  wp-content/plugins/firebase-notifications/css/send.css
  wp-content/plugins/firebase-notifications/css/wp-ms-fcm.css
  wp-content/plugins/firebase-notifications/functions/notifications.php
  wp-content/plugins/firebase-notifications/functions/rest_api.php
  wp-content/plugins/firebase-notifications/functions/settings.php
  wp-content/plugins/firebase-notifications/js/jquery-simply-countable/README.md
  wp-content/plugins/firebase-notifications/js/jquery-simply-countable/jquery.simplyCountable.js
  wp-content/plugins/firebase-notifications/js/jquery-simply-countable/simplyCountable.jquery.json
  wp-content/plugins/firebase-notifications/js/send.js
  wp-content/plugins/firebase-notifications/lang/firebase-notifications-de_DE.mo
  wp-content/plugins/firebase-notifications/lang/firebase-notifications-de_DE.po
  wp-content/plugins/firebase-notifications/notifications.php
  wp-content/plugins/firebase-notifications/plugin.php
  wp-content/plugins/firebase-notifications/templates/network_settings.php
  wp-content/plugins/firebase-notifications/templates/notification.php
  wp-content/plugins/firebase-notifications/templates/settings.php
  wp-content/plugins/ig-fcm-adjustment/plugin.php
  wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_FCM.php
  wp-content/plugins/ig-wp-api-extensions/plugin.php
Labels: pr:review required
