Repository Integreat/cms, pull requests merged in 2019-03, with the labels that each got.

#944 [ig-feedback] prevent jump to top of page when spoiler is folded out (Resolves #937)
  wp-content/plugins/ig-feedback/script.js
Labels: pr:review required, prio:low, type:enhancement

#947 [ig-feedback] sanitize feedback text
  wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
Labels: pr:review required

#952 Disable normal comment content
  wp-content/plugins/ig-fix-comment/plugin.php
Labels: prio:high
